name: Static Check

on: workflow_call

jobs:
  static_check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Core
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: core

      - name: Get Togethers
        uses: cfengine/together-javascript-action@main
        id: together
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Environment
        run: |
          sudo apt-get update && \
          sudo apt-get install -y buildah

      - name: Run The Test
        working-directory: ./core
        run: ./tests/static-check/run.sh
